# https://taskfile.dev/docs/guide
# https://taskfile.dev/reference/templating/
version: '3'
tasks:
  default: swift test

  l: |
    security find-certificate -a -Z | grep "SHA-1 hash:" # | head -n 1

  # .build/arm64-apple-macosx/debug/kc-util cert find-by-fp E57DBE3B62C0DF5C24E05468DED5026B85A1D2A0
  try: |
    swift run kc-util cert ls
    swift run kc-util cert find-by-fp E57DBE3B62C0DF5C24E05468DED5026B85A1D2A0

  v: swift run kc-util --version